too-many-arguments-threshold = 7
too-many-lines-threshold = 100
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
min-ident-chars-threshold = 1
enum-variant-size-threshold = 200
array-size-threshold = 512_000

disallowed-methods = [
    # TODO
]

disallowed-types = [
    # TODO
]

disallowed-macros = []