max_width = 100
hard_tabs = false
tab_spaces = 4
edition = "2021"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
where_single_line = false
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
match_block_trailing_comma = true
blank_lines_upper_bound = 1
chain_width = 60
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
ignore = []